AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
    - Guardfile
    - .gems/**/*

Rails:
  Enabled: true

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 100
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Metrics/AbcSize:
  Max: 30

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Delegate:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/PredicateName:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Lint/AssignmentInCondition:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 30
