defaults: &defaults
  assets:
    javascripts:
      -
    stylesheets:
      -
  nav_items:
    # to see more icons: https://colorlib.com/polygon/gentelella/icons.html
    -
      title: '.general'
      items:
        -
          icon: 'home'
          label: '.home'
          subitems:
            -
              label: '.root'
              link: root
            -
              label: '.admin_root'
              link: admin_root
        -
          icon: 'gear'
          label: .system
          subitems:
            -
              label: '.page_block'
              link: admin_page_blocks
            -
              label: '.notifications'
              link: admin_notifications
            -
              label: '.activities'
              link: admin_activities
            -
              label: '.event_logs'
              link: admin_event_logs
            -
              label: '.sidekiq'
              link: '/sidekiq'
              target: '_blank'
            -
              label: '.db_dump'
              link: 'admin_db_dump'
        -
          icon: 'users'
          label: '.roles'
          subitems:
            -
              label: '.users'
              link: admin_users
            -
              label: '.administrators'
              link: admin_administrators
        -
          icon: file
          label: .articles
          link: admin_articles
        -
          icon: 'wheelchair'
          label: '.categories.label'
          subitems:
            -
              label: '.categories.label-2'
              subitems:
                -
                  label: '.categories.index'
                  link: admin_categories
                -
                  label: '.categories.new'
                  link: '/admin/categories/new'

    -
      title: '.title-2'
      items:
        -
          icon: 'bar-chart-o'
          label: '.examples'
          link: admin_examples
          tag:
            name: '.tags.hot'
            style: 'success'
        -
          icon: 'bell'
          label: '.error-page'
          link: admin_error

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
