dbbackup:
  cron: '0 4 * * *'
  class: Tyr::DbBackupScheduler
  decription: 'Backup database'
  queue: 'default'
  enable: true
sitemap:
  cron: '0 2 * * *'
  class: Tyr::SitemapRefreshScheduler
  decription: 'Generate sitemap'
  queue: 'default'
  enable: true
bank_branch_check:
  cron: '0 0 * * SUN'
  class: 'BankBranchCheckScheduler'
  description: '檢查銀行/分行是否有更新'
  queue: 'default'
  enabled: true